# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
sudo apt-get build-dep r-cran-pbdMPI
sudo R CMD INSTALL pbdMPI --configure-args=--with-mpi=/usr/lib/openmpi