language: r
r:
- devel
os:
- linux

before_install:
- sudo apt-get update -q
- sudo apt-get install -y -q libopenmpi-dev openmpi-bin
- LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so

r_packages:
- rlecuyer
- pbdPROF
- pbdZMQ
- pbdMPI

sudo: required
dist: trusty